services:
  homeflix:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MEDIA_ROOT=/media
      - DATA_DIR=/data
      - LIBRARY_CONFIG=/data/library.yml
      - LAN_ONLY=true
    volumes:
      - /Users/pirate/Developer/homeflix/app/data:/data:rw
      - /Users/pirate/Developer/homeflix/media:/media:ro
    restart: unless-stopped
